jwt:
  interceptor:
    enabled: true  # 设置为false可禁用

# AI匹配服务配置
ai:
  api:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1
    key: sk-583a5dec7c804c32b0527ce442e04556  # 请替换为您的实际API密钥
    model: qwen3-max
    enabled: true  # 启用AI匹配
    timeout: 30000
